### PR TITLE
Compatibility with new version of youtube-dl library

### PR DESCRIPTION
**Pull request by MunGell**
Hi nonsleepr,

Here is a small fix to make this script work with latest version of youtube-dl library.
In general, it just fixes naming of external classes in several places.

### CODE REVIEW

**Comment by n1cholasv** [comment]
The changes are easy to apply- 3 line changes in one file. Without them I got an error on OS X, with them things are working great. With 10gen, for each course it creates a course folder, and one folder per week. Took me all of 5 minutes to install, fail, find this fix, apply fix, and start downloading the videos.

**Comment by nettoyeur** [comment]
Hi, MunGell!

Could you modify you patch to be compatible with non-latest versions of youtube_dl as well?

**Comment by victorhooi** [comment]
I can confirm that this patch works for me as well - without it, I wasn't able to run edu_10gen_dl.

Is there a particular reason this isn't getting merged into master?

**Comment by MunGell** [comment]
Hi @nettoyeur,

I can't see much reason to support the old version of youtube-dl API since:
- users that will  install youtibe-dl and edu_10gen_dl scripts from scratch will receive newest version of youtube-dl. Same thing with the users that will update both scripts.
- users that will update edu_10gen_dl script only will be required to update their youtube-dl, this could be done by simple change in requirements.txt.

Sorry, I also have no much time to do anything with my commit at the moment, but if someone else would want to add back-compatibility to this commit - you are welcome!

**Pull request merged**
